### ISSUE TITLE
Simple example fails, not sure where to look for the problem

### ISSUE THREAD

**Issue by schauder** [testcontainers/testcontainers-java-module-oracle-xe#10]
I've given version 1.4.3 a try with this super simple test:

```
    public class TestContainerTest {

	@Rule
	public OracleContainer oracle = new OracleContainer();

	@Test
	public void test() {
		System.out.println(oracle.getJdbcUrl());
	}
    }
```

After creating huge amounts of logs it errored with this:

```
12:29:34.275 [dockerjava-netty-1-7] DEBUG com.github.dockerjava.netty.NettyDockerCmdExecFactory$1 - [id: 0x9dd45574, L:null - R:/var/run/docker.sock] FLUSH
12:29:34.275 [dockerjava-netty-1-7] DEBUG com.github.dockerjava.netty.NettyDockerCmdExecFactory$UnixDomainSocketInitializer$3 - [id: 0x9dd45574, L:null - R:/var/run/docker.sock] FLUSH
12:29:34.277 [dockerjava-netty-1-7] DEBUG com.github.dockerjava.netty.NettyDockerCmdExecFactory$UnixDomainSocketInitializer$3 - [id: 0x9dd45574, L:null - R:/var/run/docker.sock] READ: 310B
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 48 54 54 50 2f 31 2e 31 20 34 30 34 20 4e 6f 74 |HTTP/1.1 404 Not|
|00000010| 20 46 6f 75 6e 64 0d 0a 41 70 69 2d 56 65 72 73 | Found..Api-Vers|
|00000020| 69 6f 6e 3a 20 31 2e 33 32 0d 0a 43 6f 6e 74 65 |ion: 1.32..Conte|
|00000030| 6e 74 2d 4c 65 6e 67 74 68 3a 20 39 38 0d 0a 43 |nt-Length: 98..C|
|00000040| 6f 6e 74 65 6e 74 2d 54 79 70 65 3a 20 61 70 70 |ontent-Type: app|
|00000050| 6c 69 63 61 74 69 6f 6e 2f 6a 73 6f 6e 0d 0a 44 |lication/json..D|
|00000060| 61 74 65 3a 20 46 72 69 2c 20 31 35 20 44 65 63 |ate: Fri, 15 Dec|
|00000070| 20 32 30 31 37 20 31 31 3a 32 39 3a 34 31 20 47 | 2017 11:29:41 G|
|00000080| 4d 54 0d 0a 44 6f 63 6b 65 72 2d 45 78 70 65 72 |MT..Docker-Exper|
|00000090| 69 6d 65 6e 74 61 6c 3a 20 66 61 6c 73 65 0d 0a |imental: false..|
|000000a0| 4f 73 74 79 70 65 3a 20 6c 69 6e 75 78 0d 0a 53 |Ostype: linux..S|
|000000b0| 65 72 76 65 72 3a 20 44 6f 63 6b 65 72 2f 31 37 |erver: Docker/17|
|000000c0| 2e 30 39 2e 30 2d 63 65 20 28 6c 69 6e 75 78 29 |.09.0-ce (linux)|
|000000d0| 0d 0a 0d 0a 7b 22 6d 65 73 73 61 67 65 22 3a 22 |....{"message":"|
|000000e0| 4e 6f 20 73 75 63 68 20 63 6f 6e 74 61 69 6e 65 |No such containe|
|000000f0| 72 3a 20 65 39 61 30 39 33 38 35 65 33 32 37 33 |r: e9a09385e3273|
|00000100| 64 64 39 64 36 37 63 32 37 61 31 31 39 65 33 65 |dd9d67c27a119e3e|
|00000110| 65 34 66 34 35 63 34 66 30 64 37 65 61 66 34 33 |e4f45c4f0d7eaf43|
|00000120| 32 34 64 62 32 39 34 66 33 33 64 65 34 36 34 34 |24db294f33de4644|
|00000130| 32 61 36 22 7d 0a                               |2a6"}.          |
+--------+-------------------------------------------------+----------------+
12:29:34.277 [dockerjava-netty-1-7] DEBUG com.github.dockerjava.netty.NettyDockerCmdExecFactory$1 - [id: 0x9dd45574, L:null - R:/var/run/docker.sock] READ: DefaultHttpResponse(decodeResult: success, version: HTTP/1.1)
HTTP/1.1 404 Not Found
Api-Version: 1.32
Content-Length: 98
Content-Type: application/json
Date: Fri, 15 Dec 2017 11:29:41 GMT
Docker-Experimental: false
Ostype: linux
Server: Docker/17.09.0-ce (linux)
12:29:34.277 [dockerjava-netty-1-7] DEBUG com.github.dockerjava.netty.NettyDockerCmdExecFactory$1 - [id: 0x9dd45574, L:null - R:/var/run/docker.sock] READ: DefaultLastHttpContent(data: PooledSlicedByteBuf(ridx: 0, widx: 98, cap: 98/98, unwrapped: PooledUnsafeDirectByteBuf(ridx: 310, widx: 310, cap: 1024)), decoderResult: success), 98B
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 7b 22 6d 65 73 73 61 67 65 22 3a 22 4e 6f 20 73 |{"message":"No s|
|00000010| 75 63 68 20 63 6f 6e 74 61 69 6e 65 72 3a 20 65 |uch container: e|
|00000020| 39 61 30 39 33 38 35 65 33 32 37 33 64 64 39 64 |9a09385e3273dd9d|
|00000030| 36 37 63 32 37 61 31 31 39 65 33 65 65 34 66 34 |67c27a119e3ee4f4|
|00000040| 35 63 34 66 30 64 37 65 61 66 34 33 32 34 64 62 |5c4f0d7eaf4324db|
|00000050| 32 39 34 66 33 33 64 65 34 36 34 34 32 61 36 22 |294f33de46442a6"|
|00000060| 7d 0a                                           |}.              |
+--------+-------------------------------------------------+----------------+
12:29:34.277 [dockerjava-netty-1-7] ERROR com.github.dockerjava.core.async.ResultCallbackTemplate - Error during callback
com.github.dockerjava.api.exception.NotFoundException: {"message":"No such container: e9a09385e3273dd9d67c27a119e3ee4f45c4f0d7eaf4324db294f33de46442a6"}

	at com.github.dockerjava.netty.handler.HttpResponseHandler.channelRead0(HttpResponseHandler.java:103)
	at com.github.dockerjava.netty.handler.HttpResponseHandler.channelRead0(HttpResponseHandler.java:33)
	at org.testcontainers.shaded.io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at org.testcontainers.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at org.testcontainers.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at org.testcontainers.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at org.testcontainers.shaded.io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241)
	at org.testcontainers.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at org.testcontainers.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at org.testcontainers.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at org.testcontainers.shaded.io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at org.testcontainers.shaded.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at org.testcontainers.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at org.testcontainers.shaded.io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at org.testcontainers.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at org.testcontainers.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at org.testcontainers.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at org.testcontainers.shaded.io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241)
	at org.testcontainers.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at org.testcontainers.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at org.testcontainers.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at org.testcontainers.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at org.testcontainers.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at org.testcontainers.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at org.testcontainers.shaded.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at org.testcontainers.shaded.io.netty.channel.kqueue.AbstractKQueueStreamChannel$KQueueStreamUnsafe.readReady(AbstractKQueueStreamChannel.java:608)
	at org.testcontainers.shaded.io.netty.channel.kqueue.KQueueDomainSocketChannel$KQueueDomainUnsafe.readReady(KQueueDomainSocketChannel.java:127)
	at org.testcontainers.shaded.io.netty.channel.kqueue.AbstractKQueueChannel$AbstractKQueueUnsafe.readReady(AbstractKQueueChannel.java:355)
	at org.testcontainers.shaded.io.netty.channel.kqueue.KQueueEventLoop.processReady(KQueueEventLoop.java:198)
	at org.testcontainers.shaded.io.netty.channel.kqueue.KQueueEventLoop.run(KQueueEventLoop.java:270)
	at org.testcontainers.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at org.testcontainers.shaded.io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:745)
12:29:34.277 [dockerjava-netty-1-7] DEBUG com.github.dockerjava.netty.NettyDockerCmdExecFactory$1 - [id: 0x9dd45574, L:null - R:/var/run/docker.sock] CLOSE
12:29:34.278 [dockerjava-netty-1-7] DEBUG com.github.dockerjava.netty.NettyDockerCmdExecFactory$UnixDomainSocketInitializer$3 - [id: 0x9dd45574, L:null - R:/var/run/docker.sock] CLOSE

```

**Comment by gabelilly** [comment]
I had a similar issue. Check if your project has access to a JDBC driver. I needed to add it as an additional dependency in the pom file.
